---
- name: Enable community repo in Alpine
  ansible.builtin.lineinfile:
    dest: /etc/apk/repositories
    regexp: '/community$'
    line: 'https://dl-cdn.alpinelinux.org/alpine/{{ ansible_distribution_version }}/community'
    state: present
  when: (ansible_facts['os_family'] == "Alpine")

- name: Install sudo
  ansible.builtin.package:
    name: "sudo"
    state: present