version: '3.8'

services:
  taskmanager-web:
    image: nginx:alpine
    deploy:
      replicas: 3
      restart_policy:
        condition: any
	  delay: 5s
      update_config:
        parallelism: 1
	  delay: 10s
	  order: start-first
	  failure_action: rollback
    environment:
      MONGO_HOST: mongodb
	REDIS_HOST: redis
    volumes:
      mongo-data:
	redis-data:
    networks:
      taskmanager-network:
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/api/tasks"]
      interval: 10s
      timeout: 5s
      retries: 3
	start_period: 15s

  mongodb:
    image: mongo:latest
    deploy:
      replicas: 1
      restart_policy:
        condition: any
        delay: 5s
    volumes:
      - mongo-data:/database_data
	- ./backup:/backup
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongoadmin
      MONGO_INITDB_ROOT_PASSWORD: secretpassword
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 5s
      retries: 5
	start_period: 10s

  redis:
    image: redis:alpine
    deploy:
      replicas: 1
      restart_policy:
        condition: any
        delay: 5s
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
volumes:
  redis-data:/data
    
      

networks:
  taskmanager-network
